- hosts: localhost
  connection: local

  # vars:
  #   pip_install_packages:
  #     - php_version: docker

  tasks:
      
    - name: Fetch WordPress Lemp Role
      git:
        repo: https://ro:uREXa6AXL22sDdiqbUUV@pwslab.org/ansible/wordpress-lemp.git
        dest: /root/.ansible/roles/pwslab.wlemp
        version: master
        force: yes

    - name: Check if Nginx is already installed
      stat: path=/usr/sbin/nginx
      register: nginx_exists

    - name: Check if PHP is already installed
      stat: path=/usr/bin/php
      register: php_exists

    - name: Check if MYSQL is already installed
      stat: path=/usr/bin/mysql
      register: mysql_exists

    - name: Check if version of Ubuntu
      shell: |
        lsb_release -d
      register: ubuntu_os
      ignore_errors: yes

    - name: Update php Version 
      lineinfile:
          dest: ~/.ansible/roles/wlemp/templates/nginx.conf.j2
          regexp: '^                fastcgi_pass unix:'
          line: 'fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;'
          state: present
      when:
        - ubuntu_os.stdout | regex_search("20.04")

    - name: Installing LEMP WORDPRESS
      include_role:
        name: pwslab.lemp
      when:
        - not nginx_exists.stat.exists and not php_exists.stat.exists and not mysql_exists.stat.exists
